AllCops:
  TargetRubyVersion: 2.6.2
  Exclude:
    - "config/**/*"
    - "db/**/*"
    - "bin/**/*"
    - "lib/tasks/**/*"
Metrics/LineLength:
  Max: 100
Metrics/AbcSize:
  Enabled: false
Style/GuardClause:
  Enabled: false
Metrics/BlockLength:
  Exclude:
    - "spec/**/*"
